[package]
name = "leetcode_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.5.0"
leetcoderustapi = "1.0.8"
tokio = { version = "1.12.0", features = ["full"] }
dotenvy = "0.15.0"
html2md = "0.2.14"

