indent_style = "Block"
reorder_imports = false
brace_style = "AlwaysNextLine"
color = "Always"
edition = "2021"
hard_tabs = false
max_line_length = 79
max_width = 79
comment_width = 79
tab_width = 4
empty_item_single_line = true
enum_discrim_align = true
enum_discrim_align_threshold = 79
fn_params_layout = "Vertical"
force_multiline_blocks = true
format_code_in_doc_comments = true
doc_comment_code_block_width = 79
format_strings = true
hex_literal_case = "Upper"
import_layout = "Vertical"
fn_brace_style = "AlwaysNextLine"
control_brace_style = "AlwaysSameLine"
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
